### ISSUE TITLE
Add Rmd files for Decision Trees and Stacking chapters

### ISSUE THREAD

**Issue by ledell** [ledell/useR-machine-learning-tutorial#6]
Originally this content was only Jupyter notebooks, but I received a PR which provided Rmd versions of the chapters, however two of the chapters are missing.  It would be nice to complete the set by adding the missing Rmd files.

**Comment by bgreenwell** [comment]
Submitted a pull request for the decision tree chapter, but stacking does not appear to be a valid notebook, so it won't open properly?

**Comment by ledell** [comment]
@bgreenwell You're right that somehow the stacking.ipynb got corrupted, so it's okay to start from scratch there.  This issue has been completed in this PR: https://github.com/ledell/useR-machine-learning-tutorial/pull/8
